"""sync_models

Revision ID: a8fbb027b070
Revises: c6f3e6d4b2c1
Create Date: 2026-06-16 22:32:45.635367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a8fbb027b070'
down_revision: Union[str, Sequence[str], None] = 'c6f3e6d4b2c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE scan_findings SET evidence_refs = '[]'::json WHERE evidence_refs IS NULL")
    op.execute("UPDATE scan_findings SET proof = '{}'::json WHERE proof IS NULL")
    
    op.alter_column('scan_findings', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('scan_findings', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('scan_findings', 'evidence_refs',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('scan_findings', 'proof',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scan_findings', 'proof',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('scan_findings', 'evidence_refs',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('scan_findings', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               existing_nullable=False)
    op.alter_column('scan_findings', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'candidate'::character varying"),
               existing_nullable=False)
    # ### end Alembic commands ###
